#!/usr/bin/env python3
"""
COLLATZ-NATIVE-MATH v4.5

Native Public Research Brief.

This builder creates a concise public-facing research brief for first-time readers.

It does not add theory.
It does not prove Collatz.
It does not claim Collatz is solved.
It does not claim global closure.
It does not claim global invariance.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List


VERSION = "v4.5"
ROOT = Path(__file__).resolve().parents[1]
RESULTS_DIR = ROOT / "results"

SOURCE_CONSOLIDATION = RESULTS_DIR / "native_audit_report_consolidation_certificate.json"
SOURCE_CONSOLIDATION_REPORT = RESULTS_DIR / "native_audit_report_consolidation.json"
SOURCE_LANGUAGE_SUMMARY = RESULTS_DIR / "native_language_summary_certificate.json"
SOURCE_INDEX = RESULTS_DIR / "native_language_index_certificate.json"
SOURCE_AUDIT = RESULTS_DIR / "native_artifact_consistency_audit_certificate.json"

OUTPUT_JSON = RESULTS_DIR / "native_public_research_brief.json"
OUTPUT_MD = RESULTS_DIR / "native_public_research_brief.md"
OUTPUT_CERTIFICATE = RESULTS_DIR / "native_public_research_brief_certificate.json"


def read_json(path: Path) -> Dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(path)
    return json.loads(path.read_text(encoding="utf-8"))


def build_brief() -> Dict[str, Any]:
    consolidation_cert = read_json(SOURCE_CONSOLIDATION)
    consolidation_report = read_json(SOURCE_CONSOLIDATION_REPORT)
    language_summary = read_json(SOURCE_LANGUAGE_SUMMARY)
    index_cert = read_json(SOURCE_INDEX)
    audit_cert = read_json(SOURCE_AUDIT)

    brief_sections = [
        {
            "section_id": "what_this_is",
            "title": "What this project is",
            "content": (
                "COLLATZ-NATIVE-MATH is a native structural reading of Collatz dynamics. "
                "It studies the structures generated by the transformation itself before "
                "translating them into proof-oriented language."
            ),
        },
        {
            "section_id": "what_this_is_not",
            "title": "What this project is not",
            "content": (
                "It is not a proof of Collatz. It is not a claim that Collatz is solved. "
                "It is not a theorem layer. It is not a global closure claim. It is not "
                "a global invariant claim."
            ),
        },
        {
            "section_id": "central_question",
            "title": "Central question",
            "content": "What is Collatz before it becomes a conjecture?",
        },
        {
            "section_id": "native_language_meaning",
            "title": "What native language means here",
            "content": (
                "Native language means describing Collatz through the structures produced "
                "by its own rule: expansion, discharge, debt, shadow, regeneration, "
                "compensation, closure, and obstruction."
            ),
        },
        {
            "section_id": "bounded_artifacts",
            "title": "What the bounded artifacts currently show",
            "content": (
                "The bounded artifacts show dangerous native sentence forms, danger-release "
                "behavior, dangerous stability candidates, and invariant candidates. "
                "No obstruction-relevant invariant candidate is detected in the current "
                "bounded maps."
            ),
        },
        {
            "section_id": "why_not_proof",
            "title": "Why this is not a proof",
            "content": (
                "The artifacts are bounded and descriptive. Bounded absence of obstruction "
                "does not imply global impossibility. Native grammar does not equal theorem. "
                "The termination question remains a later classical translation endpoint."
            ),
        },
        {
            "section_id": "current_integrity",
            "title": "Current repository integrity",
            "content": (
                "The repository has a passing native artifact consistency audit, a native "
                "language index, and a consolidated native audit report."
            ),
        },
        {
            "section_id": "where_next",
            "title": "Where the work continues",
            "content": (
                "The next work is to make the public brief easier to read, then continue "
                "native-language refinement without collapsing back into solution-first "
                "pressure."
            ),
        },
    ]

    public_claims_allowed = [
        "A native structural reading of the Collatz dynamics.",
        "The project starts from native description, not proof.",
        "The artifacts are bounded.",
        "The repository currently has a passing consistency audit.",
        "No obstruction-relevant invariant candidate is detected in the current bounded maps.",
    ]

    public_claims_forbidden = [
        "Collatz is solved.",
        "A proof of Collatz is provided.",
        "Global closure is proved.",
        "A global invariant is proved.",
        "Obstruction is impossible.",
        "Bounded evidence implies theorem.",
    ]

    public_brief = {
        "version": VERSION,
        "layer": "native_public_research_brief",
        "status": "public_brief_defined",
        "primary_position": "A native structural reading of the Collatz dynamics.",
        "central_question": "What is Collatz before it becomes a conjecture?",
        "mother_rule": "No solution before native language.",
        "secondary_rule": "No proof before native description.",
        "one_sentence_summary": (
            "COLLATZ-NATIVE-MATH studies Collatz as a native dynamical language before "
            "treating it as a conjecture to solve."
        ),
        "short_public_description": (
            "This project does not begin by trying to prove Collatz. It begins by asking "
            "what Collatz generates in its own structural language."
        ),
        "brief_sections": brief_sections,
        "public_claims_allowed": public_claims_allowed,
        "public_claims_forbidden": public_claims_forbidden,
        "source_versions": {
            "native_audit_report_consolidation": consolidation_cert.get("version"),
            "native_language_summary": language_summary.get("version"),
            "native_language_index": index_cert.get("version"),
            "native_artifact_consistency_audit": audit_cert.get("version"),
        },
        "source_integrity": {
            "audit_total_failure_count": audit_cert.get("total_failure_count"),
            "index_total_items": index_cert.get("total_indexed_items"),
            "index_missing_required_count": index_cert.get("missing_required_count"),
            "consolidation_status": consolidation_cert.get("status"),
            "consolidation_obstruction_relevant_invariant_candidate_count": consolidation_cert.get("obstruction_relevant_invariant_candidate_count"),
            "consolidation_invariant_candidate_count": consolidation_cert.get("invariant_candidate_count"),
            "consolidation_danger_release_invariant_candidate_count": consolidation_cert.get("danger_release_invariant_candidate_count"),
            "consolidation_dangerous_stability_invariant_candidate_count": consolidation_cert.get("dangerous_stability_invariant_candidate_count"),
            "language_summary_native_object_count": language_summary.get("native_language_object_count"),
            "language_summary_learned_pattern_count": language_summary.get("learned_pattern_count"),
        },
        "public_boundary": [
            "not_a_proof",
            "not_claimed_solved",
            "no_theorems_introduced",
            "global_closure_not_claimed",
            "global_invariant_not_claimed",
            "bounded_evidence_not_global_proof",
        ],
        "reader_first_path": [
            "README.md",
            "START_HERE.md",
            "docs/V44_PUBLIC_STATUS_REPORT.md",
            "results/native_audit_report_consolidation.md",
            "results/native_public_research_brief.md",
        ],
        "next_recommended_version": "v4.6 Public README Shortform",
        "proof_status": "not_a_proof",
        "theorem_status": "no_theorems_introduced",
        "collatz_status": "not_claimed_solved",
        "global_closure_status": "not_claimed",
        "global_invariant_status": "not_claimed",
        "not_theory_layer": True,
        "not_proof_layer": True,
    }

    return public_brief


def make_markdown(brief: Dict[str, Any]) -> str:
    lines: List[str] = []

    lines.append("# Native Public Research Brief")
    lines.append("")
    lines.append("Version: v4.5")
    lines.append("")
    lines.append("## One-sentence summary")
    lines.append("")
    lines.append(brief["one_sentence_summary"])
    lines.append("")
    lines.append("## Short public description")
    lines.append("")
    lines.append(brief["short_public_description"])
    lines.append("")
    lines.append("## Central question")
    lines.append("")
    lines.append("    " + brief["central_question"])
    lines.append("")
    lines.append("## Core rule")
    lines.append("")
    lines.append("    " + brief["mother_rule"])
    lines.append("")
    lines.append("## Sections")
    lines.append("")

    for section in brief["brief_sections"]:
        lines.append(f"### {section['title']}")
        lines.append("")
        lines.append(section["content"])
        lines.append("")

    lines.append("## Allowed public claims")
    lines.append("")
    for claim in brief["public_claims_allowed"]:
        lines.append(f"- {claim}")
    lines.append("")

    lines.append("## Forbidden public claims")
    lines.append("")
    for claim in brief["public_claims_forbidden"]:
        lines.append(f"- {claim}")
    lines.append("")

    lines.append("## Source integrity")
    lines.append("")
    for key, value in brief["source_integrity"].items():
        lines.append(f"- {key}: {value}")
    lines.append("")

    lines.append("## Boundary")
    lines.append("")
    lines.append(f"- proof_status: {brief['proof_status']}")
    lines.append(f"- theorem_status: {brief['theorem_status']}")
    lines.append(f"- collatz_status: {brief['collatz_status']}")
    lines.append(f"- global_closure_status: {brief['global_closure_status']}")
    lines.append(f"- global_invariant_status: {brief['global_invariant_status']}")
    lines.append("")

    lines.append("## Reader first path")
    lines.append("")
    for item in brief["reader_first_path"]:
        lines.append(f"- {item}")
    lines.append("")

    lines.append("## Next")
    lines.append("")
    lines.append(brief["next_recommended_version"])
    lines.append("")

    return "\n".join(lines)


def make_certificate(brief: Dict[str, Any]) -> Dict[str, Any]:
    integrity = brief["source_integrity"]

    return {
        "version": VERSION,
        "certificate_type": "native_public_research_brief_certificate",
        "status": brief["status"],
        "primary_position": brief["primary_position"],
        "central_question": brief["central_question"],
        "mother_rule": brief["mother_rule"],
        "brief_section_count": len(brief["brief_sections"]),
        "allowed_public_claim_count": len(brief["public_claims_allowed"]),
        "forbidden_public_claim_count": len(brief["public_claims_forbidden"]),
        "reader_first_path_count": len(brief["reader_first_path"]),
        "audit_total_failure_count": integrity.get("audit_total_failure_count"),
        "index_total_items": integrity.get("index_total_items"),
        "index_missing_required_count": integrity.get("index_missing_required_count"),
        "consolidation_status": integrity.get("consolidation_status"),
        "obstruction_relevant_invariant_candidate_count": integrity.get("consolidation_obstruction_relevant_invariant_candidate_count"),
        "invariant_candidate_count": integrity.get("consolidation_invariant_candidate_count"),
        "danger_release_invariant_candidate_count": integrity.get("consolidation_danger_release_invariant_candidate_count"),
        "dangerous_stability_invariant_candidate_count": integrity.get("consolidation_dangerous_stability_invariant_candidate_count"),
        "proof_status": brief["proof_status"],
        "theorem_status": brief["theorem_status"],
        "collatz_status": brief["collatz_status"],
        "global_closure_status": brief["global_closure_status"],
        "global_invariant_status": brief["global_invariant_status"],
        "not_theory_layer": brief["not_theory_layer"],
        "not_proof_layer": brief["not_proof_layer"],
        "next_recommended_version": brief["next_recommended_version"],
    }


def main() -> None:
    print("=" * 80)
    print("COLLATZ-NATIVE-MATH v4.5")
    print("=" * 80)
    print("Native Public Research Brief")
    print("=" * 80)

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)

    brief = build_brief()
    markdown = make_markdown(brief)
    certificate = make_certificate(brief)

    OUTPUT_JSON.write_text(json.dumps(brief, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    OUTPUT_MD.write_text(markdown + "\n", encoding="utf-8")
    OUTPUT_CERTIFICATE.write_text(json.dumps(certificate, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    print(f"status: {brief['status']}")
    print(f"primary_position: {brief['primary_position']}")
    print(f"central_question: {brief['central_question']}")
    print(f"audit_total_failure_count: {certificate['audit_total_failure_count']}")
    print(f"index_total_items: {certificate['index_total_items']}")
    print(f"obstruction_relevant_invariant_candidate_count: {certificate['obstruction_relevant_invariant_candidate_count']}")
    print(f"brief_section_count: {certificate['brief_section_count']}")
    print(f"proof_status: {certificate['proof_status']}")
    print(f"collatz_status: {certificate['collatz_status']}")
    print(f"mother_rule: {certificate['mother_rule']}")
    print(f"next: {certificate['next_recommended_version']}")
    print(f"Wrote JSON brief to: {OUTPUT_JSON.relative_to(ROOT)}")
    print(f"Wrote Markdown brief to: {OUTPUT_MD.relative_to(ROOT)}")
    print(f"Wrote certificate to: {OUTPUT_CERTIFICATE.relative_to(ROOT)}")
    print("=" * 80)


if __name__ == "__main__":
    main()
